// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AuditLog struct {
	ID            int64          `json:"id"`
	Timestamp     string         `json:"timestamp"`
	Username      string         `json:"username"`
	IpAddress     sql.NullString `json:"ip_address"`
	Action        string         `json:"action"`
	ImpactedTable string         `json:"impacted_table"`
	OldValues     sql.NullString `json:"old_values"`
	NewValues     sql.NullString `json:"new_values"`
}

type Delivery struct {
	ID             int64          `json:"id"`
	DeliveryID     string         `json:"delivery_id"`
	NotificationID string         `json:"notification_id"`
	Group          sql.NullString `json:"group"`
	Member         sql.NullString `json:"member"`
	Destination    sql.NullString `json:"destination"`
	Channel        string         `json:"channel"`
	Status         string         `json:"status"`
	EmailTemplate  sql.NullString `json:"email_template"`
	EmailVars      sql.NullString `json:"email_vars"`
	Attempt        int64          `json:"attempt"`
	PollAttempts   int64          `json:"poll_attempts"`
	ErrorMessage   sql.NullString `json:"error_message"`
	SentAt         string         `json:"sent_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	TwilioSid      sql.NullString `json:"twilio_sid"`
}

type EmailTemplate struct {
	ID           int64          `json:"id"`
	TemplateName string         `json:"template_name"`
	Subject      string         `json:"subject"`
	Body         string         `json:"body"`
	RequiredVars string         `json:"required_vars"`
	Description  sql.NullString `json:"description"`
}

type Event struct {
	ID               int64          `json:"id"`
	EventID          string         `json:"event_id"`
	EventUrl         sql.NullString `json:"event_url"`
	EventName        sql.NullString `json:"event_name"`
	EventDescription sql.NullString `json:"event_description"`
	EventSeverity    sql.NullString `json:"event_severity"`
	StartTime        string         `json:"start_time"`
	EndTime          sql.NullString `json:"end_time"`
	CreatedBy        sql.NullString `json:"created_by"`
	CreatedAt        string         `json:"created_at"`
	ModifiedBy       sql.NullString `json:"modified_by"`
	ModifiedAt       sql.NullString `json:"modified_at"`
}

type GroupMember struct {
	GroupName   string         `json:"group_name"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Email       sql.NullString `json:"email"`
	Mobile      sql.NullString `json:"mobile"`
	Work        sql.NullString `json:"work"`
	SyncedAt    string         `json:"synced_at"`
}

type Notification struct {
	ID             int64          `json:"id"`
	NotificationID string         `json:"notification_id"`
	EventID        string         `json:"event_id"`
	Groups         sql.NullString `json:"groups"`
	Destinations   sql.NullString `json:"destinations"`
	Channels       sql.NullString `json:"channels"`
	Message        string         `json:"message"`
	Status         string         `json:"status"`
	ErrorMessage   sql.NullString `json:"error_message"`
	MemberCount    int64          `json:"member_count"`
	EmailTemplate  sql.NullString `json:"email_template"`
	EmailVars      sql.NullString `json:"email_vars"`
	CreatedAt      string         `json:"created_at"`
	CreatedBy      sql.NullString `json:"created_by"`
}

type SmsSubscription struct {
	Username     string `json:"username"`
	Phone        string `json:"phone"`
	SubscribedAt string `json:"subscribed_at"`
}

type SyncGroup struct {
	ID        int64  `json:"id"`
	GroupName string `json:"group_name"`
	CreatedAt string `json:"created_at"`
	CreatedBy string `json:"created_by"`
}
