// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type AuditLog struct {
	ID            int64          `json:"id"`
	Timestamp     string         `json:"timestamp"`
	Username      string         `json:"username"`
	IpAddress     sql.NullString `json:"ip_address"`
	Action        string         `json:"action"`
	ImpactedTable string         `json:"impacted_table"`
	OldValues     sql.NullString `json:"old_values"`
	NewValues     sql.NullString `json:"new_values"`
}

type Delivery struct {
	ID             int64          `json:"id"`
	DeliveryID     string         `json:"delivery_id"`
	NotificationID string         `json:"notification_id"`
	Group          string         `json:"group"`
	Member         string         `json:"member"`
	Channel        string         `json:"channel"`
	Status         string         `json:"status"`
	EmailTemplate  sql.NullString `json:"email_template"`
	EmailVars      sql.NullString `json:"email_vars"`
	Attempt        int64          `json:"attempt"`
	ErrorMessage   sql.NullString `json:"error_message"`
	SentAt         string         `json:"sent_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	PollAttempts   int64          `json:"poll_attempts"`
}

type EmailTemplate struct {
	ID           int64          `json:"id"`
	TemplateName string         `json:"template_name"`
	Subject      string         `json:"subject"`
	Body         string         `json:"body"`
	RequiredVars string         `json:"required_vars"`
	Description  sql.NullString `json:"description"`
}

type Event struct {
	ID               int64          `json:"id"`
	EventID          string         `json:"event_id"`
	EventUrl         sql.NullString `json:"event_url"`
	EventName        sql.NullString `json:"event_name"`
	EventDescription sql.NullString `json:"event_description"`
	EventSeverity    sql.NullString `json:"event_severity"`
	StartTime        string         `json:"start_time"`
	EndTime          sql.NullString `json:"end_time"`
}

type GroupMember struct {
	GroupName   string         `json:"group_name"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Email       sql.NullString `json:"email"`
	Mobile      sql.NullString `json:"mobile"`
	Work        sql.NullString `json:"work"`
	SyncedAt    string         `json:"synced_at"`
}

type Notification struct {
	ID             int64          `json:"id"`
	NotificationID string         `json:"notification_id"`
	EventID        string         `json:"event_id"`
	Groups         string         `json:"groups"`
	Channels       string         `json:"channels"`
	Message        string         `json:"message"`
	MemberCount    int64          `json:"member_count"`
	EmailTemplate  sql.NullString `json:"email_template"`
	EmailVars      sql.NullString `json:"email_vars"`
	CreatedAt      string         `json:"created_at"`
	Status         string         `json:"status"`
	ErrorMessage   sql.NullString `json:"error_message"`
}

type SyncGroup struct {
	ID        int64  `json:"id"`
	GroupName string `json:"group_name"`
	CreatedAt string `json:"created_at"`
	CreatedBy string `json:"created_by"`
}
