// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteEmailTemplate(ctx context.Context, templateName string) error
	DeleteGroupMembers(ctx context.Context, groupName string) error
	DeleteSMSSubscription(ctx context.Context, username string) error
	DeleteSyncGroup(ctx context.Context, groupName string) error
	GetDeliveryByDeliveryID(ctx context.Context, deliveryID string) (Delivery, error)
	GetEmailTemplateByName(ctx context.Context, templateName string) (EmailTemplate, error)
	GetEventByEventID(ctx context.Context, eventID string) (Event, error)
	GetEventByID(ctx context.Context, id int64) (Event, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetNotificationByID(ctx context.Context, id int64) (Notification, error)
	GetNotificationByNotificationID(ctx context.Context, notificationID string) (Notification, error)
	// sms_subscriptions
	GetSMSSubscription(ctx context.Context, lower string) (SmsSubscription, error)
	GetSMSSubscriptionByPhone(ctx context.Context, phone string) (SmsSubscription, error)
	GetSyncGroup(ctx context.Context, groupName string) (SyncGroup, error)
	IncrementDeliveryAttempt(ctx context.Context, arg IncrementDeliveryAttemptParams) error
	// Atomically increments poll_attempts and returns the updated delivery row,
	// allowing the caller to decide whether the attempt limit has been reached.
	IncrementPollAttempts(ctx context.Context, deliveryID string) (Delivery, error)
	// audit_log
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// deliveries
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (Delivery, error)
	InsertDestinationDelivery(ctx context.Context, arg InsertDestinationDeliveryParams) (Delivery, error)
	// email_templates
	InsertEmailTemplate(ctx context.Context, arg InsertEmailTemplateParams) (EmailTemplate, error)
	// events
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	// group_members
	InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error
	// notifications
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	InsertSMSSubscription(ctx context.Context, arg InsertSMSSubscriptionParams) error
	InsertSyncGroup(ctx context.Context, arg InsertSyncGroupParams) (SyncGroup, error)
	ListAuditLogFiltered(ctx context.Context, arg ListAuditLogFilteredParams) ([]AuditLog, error)
	ListDeliveriesByNotificationID(ctx context.Context, notificationID string) ([]Delivery, error)
	ListDistinctGroupNames(ctx context.Context) ([]string, error)
	ListEmailTemplates(ctx context.Context) ([]EmailTemplate, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsFiltered(ctx context.Context, arg ListEventsFilteredParams) ([]Event, error)
	ListGroupMembers(ctx context.Context, groupName string) ([]GroupMember, error)
	// Non-terminal Twilio message statuses: accepted, scheduled, queued, sending, sent
	// "sent" means the carrier accepted the message but delivery is not yet confirmed;
	// polling continues until "delivered" or a terminal failure status is received.
	ListInFlightSMSDeliveries(ctx context.Context) ([]Delivery, error)
	// Non-terminal Twilio voice statuses: queued, ringing, in-progress
	ListInFlightVoiceDeliveries(ctx context.Context) ([]Delivery, error)
	ListNotificationsByEventID(ctx context.Context, eventID string) ([]Notification, error)
	ListPollFailedDeliveries(ctx context.Context) ([]Delivery, error)
	ListSMSSubscriptions(ctx context.Context) ([]SmsSubscription, error)
	// sync_groups
	ListSyncGroups(ctx context.Context) ([]SyncGroup, error)
	ResetPollAttempts(ctx context.Context) error
	// Records an error on a delivery without changing its status or completion time.
	// Called when the application fails to dispatch to the delivery service (e.g.
	// network error calling Twilio or SMTP), as distinct from a terminal status
	// returned by the provider.
	UpdateDeliveryError(ctx context.Context, arg UpdateDeliveryErrorParams) error
	// error_message should include the Twilio error code when applicable,
	// e.g. "queue overflow: 30001"
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error
	UpdateEmailTemplate(ctx context.Context, arg UpdateEmailTemplateParams) error
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateEventEndTime(ctx context.Context, arg UpdateEventEndTimeParams) error
	UpdateNotificationMemberCount(ctx context.Context, arg UpdateNotificationMemberCountParams) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
}

var _ Querier = (*Queries)(nil)
