// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteEmailTemplate = `-- name: DeleteEmailTemplate :exec
DELETE FROM email_templates WHERE template_name = ?
`

func (q *Queries) DeleteEmailTemplate(ctx context.Context, templateName string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailTemplate, templateName)
	return err
}

const deleteGroupMembers = `-- name: DeleteGroupMembers :exec
DELETE FROM group_members WHERE group_name = ?
`

func (q *Queries) DeleteGroupMembers(ctx context.Context, groupName string) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMembers, groupName)
	return err
}

const deleteSMSSubscription = `-- name: DeleteSMSSubscription :exec
DELETE FROM sms_subscriptions WHERE username = ?
`

func (q *Queries) DeleteSMSSubscription(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteSMSSubscription, username)
	return err
}

const deleteSyncGroup = `-- name: DeleteSyncGroup :exec
DELETE FROM sync_groups WHERE group_name = ?
`

func (q *Queries) DeleteSyncGroup(ctx context.Context, groupName string) error {
	_, err := q.db.ExecContext(ctx, deleteSyncGroup, groupName)
	return err
}

const getDeliveryByDeliveryID = `-- name: GetDeliveryByDeliveryID :one
SELECT id, delivery_id, notification_id, "group", member, destination, channel, status, email_template, email_vars, attempt, poll_attempts, error_message, sent_at, completed_at, twilio_sid FROM deliveries WHERE delivery_id = ?
`

func (q *Queries) GetDeliveryByDeliveryID(ctx context.Context, deliveryID string) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryByDeliveryID, deliveryID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.NotificationID,
		&i.Group,
		&i.Member,
		&i.Destination,
		&i.Channel,
		&i.Status,
		&i.EmailTemplate,
		&i.EmailVars,
		&i.Attempt,
		&i.PollAttempts,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CompletedAt,
		&i.TwilioSid,
	)
	return i, err
}

const getEmailTemplateByName = `-- name: GetEmailTemplateByName :one
SELECT id, template_name, subject, body, required_vars, description FROM email_templates WHERE template_name = ?
`

func (q *Queries) GetEmailTemplateByName(ctx context.Context, templateName string) (EmailTemplate, error) {
	row := q.db.QueryRowContext(ctx, getEmailTemplateByName, templateName)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateName,
		&i.Subject,
		&i.Body,
		&i.RequiredVars,
		&i.Description,
	)
	return i, err
}

const getEventByEventID = `-- name: GetEventByEventID :one
SELECT id, event_id, event_url, event_name, event_description, event_severity, start_time, end_time, created_by, created_at, modified_by, modified_at FROM events WHERE event_id = ?
`

func (q *Queries) GetEventByEventID(ctx context.Context, eventID string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByEventID, eventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventUrl,
		&i.EventName,
		&i.EventDescription,
		&i.EventSeverity,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, event_id, event_url, event_name, event_description, event_severity, start_time, end_time, created_by, created_at, modified_by, modified_at FROM events WHERE id = ?
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventUrl,
		&i.EventName,
		&i.EventDescription,
		&i.EventSeverity,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_name, username, display_name, email, mobile, work, synced_at FROM group_members WHERE group_name = ? AND username = ?
`

type GetGroupMemberParams struct {
	GroupName string `json:"group_name"`
	Username  string `json:"username"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, getGroupMember, arg.GroupName, arg.Username)
	var i GroupMember
	err := row.Scan(
		&i.GroupName,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Mobile,
		&i.Work,
		&i.SyncedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, notification_id, event_id, "groups", destinations, channels, message, status, error_message, member_count, email_template, email_vars, created_at, created_by FROM notifications WHERE id = ?
`

func (q *Queries) GetNotificationByID(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.EventID,
		&i.Groups,
		&i.Destinations,
		&i.Channels,
		&i.Message,
		&i.Status,
		&i.ErrorMessage,
		&i.MemberCount,
		&i.EmailTemplate,
		&i.EmailVars,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getNotificationByNotificationID = `-- name: GetNotificationByNotificationID :one
SELECT id, notification_id, event_id, "groups", destinations, channels, message, status, error_message, member_count, email_template, email_vars, created_at, created_by FROM notifications WHERE notification_id = ?
`

func (q *Queries) GetNotificationByNotificationID(ctx context.Context, notificationID string) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByNotificationID, notificationID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.EventID,
		&i.Groups,
		&i.Destinations,
		&i.Channels,
		&i.Message,
		&i.Status,
		&i.ErrorMessage,
		&i.MemberCount,
		&i.EmailTemplate,
		&i.EmailVars,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getSMSSubscription = `-- name: GetSMSSubscription :one

SELECT username, phone, subscribed_at FROM sms_subscriptions WHERE LOWER(username) = LOWER(?)
`

// sms_subscriptions
func (q *Queries) GetSMSSubscription(ctx context.Context, lower string) (SmsSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSMSSubscription, lower)
	var i SmsSubscription
	err := row.Scan(&i.Username, &i.Phone, &i.SubscribedAt)
	return i, err
}

const getSMSSubscriptionByPhone = `-- name: GetSMSSubscriptionByPhone :one
SELECT username, phone, subscribed_at FROM sms_subscriptions WHERE phone = ?
`

func (q *Queries) GetSMSSubscriptionByPhone(ctx context.Context, phone string) (SmsSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSMSSubscriptionByPhone, phone)
	var i SmsSubscription
	err := row.Scan(&i.Username, &i.Phone, &i.SubscribedAt)
	return i, err
}

const getSyncGroup = `-- name: GetSyncGroup :one
SELECT id, group_name, created_at, created_by FROM sync_groups WHERE group_name = ? LIMIT 1
`

func (q *Queries) GetSyncGroup(ctx context.Context, groupName string) (SyncGroup, error) {
	row := q.db.QueryRowContext(ctx, getSyncGroup, groupName)
	var i SyncGroup
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const incrementDeliveryAttempt = `-- name: IncrementDeliveryAttempt :exec
UPDATE deliveries
SET attempt = attempt + 1, sent_at = ?
WHERE delivery_id = ?
`

type IncrementDeliveryAttemptParams struct {
	SentAt     string `json:"sent_at"`
	DeliveryID string `json:"delivery_id"`
}

func (q *Queries) IncrementDeliveryAttempt(ctx context.Context, arg IncrementDeliveryAttemptParams) error {
	_, err := q.db.ExecContext(ctx, incrementDeliveryAttempt, arg.SentAt, arg.DeliveryID)
	return err
}

const incrementPollAttempts = `-- name: IncrementPollAttempts :one
UPDATE deliveries
SET poll_attempts = poll_attempts + 1
WHERE delivery_id = ?
RETURNING id, delivery_id, notification_id, "group", member, destination, channel, status, email_template, email_vars, attempt, poll_attempts, error_message, sent_at, completed_at, twilio_sid
`

// Atomically increments poll_attempts and returns the updated delivery row,
// allowing the caller to decide whether the attempt limit has been reached.
func (q *Queries) IncrementPollAttempts(ctx context.Context, deliveryID string) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, incrementPollAttempts, deliveryID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.NotificationID,
		&i.Group,
		&i.Member,
		&i.Destination,
		&i.Channel,
		&i.Status,
		&i.EmailTemplate,
		&i.EmailVars,
		&i.Attempt,
		&i.PollAttempts,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CompletedAt,
		&i.TwilioSid,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_log (timestamp, username, ip_address, action, impacted_table, old_values, new_values)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	Timestamp     string         `json:"timestamp"`
	Username      string         `json:"username"`
	IpAddress     sql.NullString `json:"ip_address"`
	Action        string         `json:"action"`
	ImpactedTable string         `json:"impacted_table"`
	OldValues     sql.NullString `json:"old_values"`
	NewValues     sql.NullString `json:"new_values"`
}

// audit_log
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.Timestamp,
		arg.Username,
		arg.IpAddress,
		arg.Action,
		arg.ImpactedTable,
		arg.OldValues,
		arg.NewValues,
	)
	return err
}

const insertDelivery = `-- name: InsertDelivery :one

INSERT INTO deliveries (delivery_id, notification_id, "group", member, channel, status, email_template, email_vars, attempt, sent_at, twilio_sid)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, delivery_id, notification_id, "group", member, destination, channel, status, email_template, email_vars, attempt, poll_attempts, error_message, sent_at, completed_at, twilio_sid
`

type InsertDeliveryParams struct {
	DeliveryID     string         `json:"delivery_id"`
	NotificationID string         `json:"notification_id"`
	Group          sql.NullString `json:"group"`
	Member         sql.NullString `json:"member"`
	Channel        string         `json:"channel"`
	Status         string         `json:"status"`
	EmailTemplate  sql.NullString `json:"email_template"`
	EmailVars      sql.NullString `json:"email_vars"`
	Attempt        int64          `json:"attempt"`
	SentAt         string         `json:"sent_at"`
	TwilioSid      sql.NullString `json:"twilio_sid"`
}

// deliveries
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, insertDelivery,
		arg.DeliveryID,
		arg.NotificationID,
		arg.Group,
		arg.Member,
		arg.Channel,
		arg.Status,
		arg.EmailTemplate,
		arg.EmailVars,
		arg.Attempt,
		arg.SentAt,
		arg.TwilioSid,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.NotificationID,
		&i.Group,
		&i.Member,
		&i.Destination,
		&i.Channel,
		&i.Status,
		&i.EmailTemplate,
		&i.EmailVars,
		&i.Attempt,
		&i.PollAttempts,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CompletedAt,
		&i.TwilioSid,
	)
	return i, err
}

const insertDestinationDelivery = `-- name: InsertDestinationDelivery :one
INSERT INTO deliveries (delivery_id, notification_id, destination, channel, status, email_template, email_vars, attempt, sent_at, twilio_sid)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, delivery_id, notification_id, "group", member, destination, channel, status, email_template, email_vars, attempt, poll_attempts, error_message, sent_at, completed_at, twilio_sid
`

type InsertDestinationDeliveryParams struct {
	DeliveryID     string         `json:"delivery_id"`
	NotificationID string         `json:"notification_id"`
	Destination    sql.NullString `json:"destination"`
	Channel        string         `json:"channel"`
	Status         string         `json:"status"`
	EmailTemplate  sql.NullString `json:"email_template"`
	EmailVars      sql.NullString `json:"email_vars"`
	Attempt        int64          `json:"attempt"`
	SentAt         string         `json:"sent_at"`
	TwilioSid      sql.NullString `json:"twilio_sid"`
}

func (q *Queries) InsertDestinationDelivery(ctx context.Context, arg InsertDestinationDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, insertDestinationDelivery,
		arg.DeliveryID,
		arg.NotificationID,
		arg.Destination,
		arg.Channel,
		arg.Status,
		arg.EmailTemplate,
		arg.EmailVars,
		arg.Attempt,
		arg.SentAt,
		arg.TwilioSid,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.NotificationID,
		&i.Group,
		&i.Member,
		&i.Destination,
		&i.Channel,
		&i.Status,
		&i.EmailTemplate,
		&i.EmailVars,
		&i.Attempt,
		&i.PollAttempts,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CompletedAt,
		&i.TwilioSid,
	)
	return i, err
}

const insertEmailTemplate = `-- name: InsertEmailTemplate :one

INSERT INTO email_templates (template_name, subject, body, required_vars, description)
VALUES (?, ?, ?, ?, ?)
RETURNING id, template_name, subject, body, required_vars, description
`

type InsertEmailTemplateParams struct {
	TemplateName string         `json:"template_name"`
	Subject      string         `json:"subject"`
	Body         string         `json:"body"`
	RequiredVars string         `json:"required_vars"`
	Description  sql.NullString `json:"description"`
}

// email_templates
func (q *Queries) InsertEmailTemplate(ctx context.Context, arg InsertEmailTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRowContext(ctx, insertEmailTemplate,
		arg.TemplateName,
		arg.Subject,
		arg.Body,
		arg.RequiredVars,
		arg.Description,
	)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateName,
		&i.Subject,
		&i.Body,
		&i.RequiredVars,
		&i.Description,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one

INSERT INTO events (event_id, event_url, event_name, event_description, event_severity, start_time, end_time, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, event_id, event_url, event_name, event_description, event_severity, start_time, end_time, created_by, created_at, modified_by, modified_at
`

type InsertEventParams struct {
	EventID          string         `json:"event_id"`
	EventUrl         sql.NullString `json:"event_url"`
	EventName        sql.NullString `json:"event_name"`
	EventDescription sql.NullString `json:"event_description"`
	EventSeverity    sql.NullString `json:"event_severity"`
	StartTime        string         `json:"start_time"`
	EndTime          sql.NullString `json:"end_time"`
	CreatedBy        sql.NullString `json:"created_by"`
	CreatedAt        string         `json:"created_at"`
}

// events
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.EventID,
		arg.EventUrl,
		arg.EventName,
		arg.EventDescription,
		arg.EventSeverity,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventUrl,
		&i.EventName,
		&i.EventDescription,
		&i.EventSeverity,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
	)
	return i, err
}

const insertGroupMember = `-- name: InsertGroupMember :exec

INSERT INTO group_members (group_name, username, display_name, email, mobile, work, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertGroupMemberParams struct {
	GroupName   string         `json:"group_name"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Email       sql.NullString `json:"email"`
	Mobile      sql.NullString `json:"mobile"`
	Work        sql.NullString `json:"work"`
	SyncedAt    string         `json:"synced_at"`
}

// group_members
func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertGroupMember,
		arg.GroupName,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Mobile,
		arg.Work,
		arg.SyncedAt,
	)
	return err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications
    (notification_id, event_id, groups, destinations, channels, message, member_count,
     email_template, email_vars, created_at, created_by, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, notification_id, event_id, "groups", destinations, channels, message, status, error_message, member_count, email_template, email_vars, created_at, created_by
`

type InsertNotificationParams struct {
	NotificationID string         `json:"notification_id"`
	EventID        string         `json:"event_id"`
	Groups         sql.NullString `json:"groups"`
	Destinations   sql.NullString `json:"destinations"`
	Channels       sql.NullString `json:"channels"`
	Message        string         `json:"message"`
	MemberCount    int64          `json:"member_count"`
	EmailTemplate  sql.NullString `json:"email_template"`
	EmailVars      sql.NullString `json:"email_vars"`
	CreatedAt      string         `json:"created_at"`
	CreatedBy      sql.NullString `json:"created_by"`
	Status         string         `json:"status"`
}

// notifications
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.NotificationID,
		arg.EventID,
		arg.Groups,
		arg.Destinations,
		arg.Channels,
		arg.Message,
		arg.MemberCount,
		arg.EmailTemplate,
		arg.EmailVars,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.Status,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.EventID,
		&i.Groups,
		&i.Destinations,
		&i.Channels,
		&i.Message,
		&i.Status,
		&i.ErrorMessage,
		&i.MemberCount,
		&i.EmailTemplate,
		&i.EmailVars,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertSMSSubscription = `-- name: InsertSMSSubscription :exec
INSERT INTO sms_subscriptions (username, phone, subscribed_at) VALUES (?, ?, ?)
`

type InsertSMSSubscriptionParams struct {
	Username     string `json:"username"`
	Phone        string `json:"phone"`
	SubscribedAt string `json:"subscribed_at"`
}

func (q *Queries) InsertSMSSubscription(ctx context.Context, arg InsertSMSSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertSMSSubscription, arg.Username, arg.Phone, arg.SubscribedAt)
	return err
}

const insertSyncGroup = `-- name: InsertSyncGroup :one
INSERT INTO sync_groups (group_name, created_by) VALUES (?, ?) RETURNING id, group_name, created_at, created_by
`

type InsertSyncGroupParams struct {
	GroupName string `json:"group_name"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) InsertSyncGroup(ctx context.Context, arg InsertSyncGroupParams) (SyncGroup, error) {
	row := q.db.QueryRowContext(ctx, insertSyncGroup, arg.GroupName, arg.CreatedBy)
	var i SyncGroup
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAuditLogFiltered = `-- name: ListAuditLogFiltered :many
SELECT id, timestamp, username, ip_address, "action", impacted_table, old_values, new_values FROM audit_log
WHERE (?1 = '' OR username = ?1)
  AND (?2 = '' OR timestamp >= ?2)
  AND (?3 = '' OR timestamp <= ?3)
ORDER BY timestamp DESC
LIMIT ?5 OFFSET ?4
`

type ListAuditLogFilteredParams struct {
	Username interface{} `json:"username"`
	FromTime interface{} `json:"from_time"`
	ToTime   interface{} `json:"to_time"`
	Offset   int64       `json:"offset"`
	Limit    int64       `json:"limit"`
}

func (q *Queries) ListAuditLogFiltered(ctx context.Context, arg ListAuditLogFilteredParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogFiltered,
		arg.Username,
		arg.FromTime,
		arg.ToTime,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Username,
			&i.IpAddress,
			&i.Action,
			&i.ImpactedTable,
			&i.OldValues,
			&i.NewValues,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByNotificationID = `-- name: ListDeliveriesByNotificationID :many
SELECT id, delivery_id, notification_id, "group", member, destination, channel, status, email_template, email_vars, attempt, poll_attempts, error_message, sent_at, completed_at, twilio_sid FROM deliveries WHERE notification_id = ? ORDER BY sent_at DESC
`

func (q *Queries) ListDeliveriesByNotificationID(ctx context.Context, notificationID string) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveriesByNotificationID, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.NotificationID,
			&i.Group,
			&i.Member,
			&i.Destination,
			&i.Channel,
			&i.Status,
			&i.EmailTemplate,
			&i.EmailVars,
			&i.Attempt,
			&i.PollAttempts,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CompletedAt,
			&i.TwilioSid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctGroupNames = `-- name: ListDistinctGroupNames :many
SELECT DISTINCT group_name FROM group_members ORDER BY group_name
`

func (q *Queries) ListDistinctGroupNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctGroupNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailTemplates = `-- name: ListEmailTemplates :many
SELECT id, template_name, subject, body, required_vars, description FROM email_templates ORDER BY template_name
`

func (q *Queries) ListEmailTemplates(ctx context.Context) ([]EmailTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listEmailTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailTemplate
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TemplateName,
			&i.Subject,
			&i.Body,
			&i.RequiredVars,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, event_id, event_url, event_name, event_description, event_severity, start_time, end_time, created_by, created_at, modified_by, modified_at FROM events ORDER BY start_time DESC LIMIT ? OFFSET ?
`

type ListEventsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventUrl,
			&i.EventName,
			&i.EventDescription,
			&i.EventSeverity,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsFiltered = `-- name: ListEventsFiltered :many
SELECT id, event_id, event_url, event_name, event_description, event_severity, start_time, end_time, created_by, created_at, modified_by, modified_at FROM events
WHERE (?1 = '' OR start_time >= ?1)
  AND (?2 = '' OR start_time <= ?2)
  AND (?3 = '' OR LOWER(event_id) LIKE '%' || LOWER(?3) || '%')
  AND (?4 = '' OR LOWER(event_name) LIKE '%' || LOWER(?4) || '%')
  AND (?5 = '' OR LOWER(event_description) LIKE '%' || LOWER(?5) || '%')
  AND (?6 = '' OR event_severity = ?6)
  AND (?7 = '' OR LOWER(created_by) LIKE '%' || LOWER(?7) || '%')
  AND (?8 = '' OR (?8 = 'active' AND end_time IS NULL) OR (?8 = 'ended' AND end_time IS NOT NULL))
ORDER BY start_time DESC
LIMIT ?10 OFFSET ?9
`

type ListEventsFilteredParams struct {
	StartFrom   interface{} `json:"start_from"`
	StartTo     interface{} `json:"start_to"`
	EventID     interface{} `json:"event_id"`
	EventName   interface{} `json:"event_name"`
	Description interface{} `json:"description"`
	Severity    interface{} `json:"severity"`
	CreatedBy   interface{} `json:"created_by"`
	Status      interface{} `json:"status"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) ListEventsFiltered(ctx context.Context, arg ListEventsFilteredParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsFiltered,
		arg.StartFrom,
		arg.StartTo,
		arg.EventID,
		arg.EventName,
		arg.Description,
		arg.Severity,
		arg.CreatedBy,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventUrl,
			&i.EventName,
			&i.EventDescription,
			&i.EventSeverity,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ModifiedBy,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT group_name, username, display_name, email, mobile, work, synced_at FROM group_members WHERE group_name = ? ORDER BY username
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupName string) ([]GroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.GroupName,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Mobile,
			&i.Work,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInFlightSMSDeliveries = `-- name: ListInFlightSMSDeliveries :many
SELECT id, delivery_id, notification_id, "group", member, destination, channel, status, email_template, email_vars, attempt, poll_attempts, error_message, sent_at, completed_at, twilio_sid FROM deliveries
WHERE channel = 'sms'
  AND status IN ('accepted', 'scheduled', 'queued', 'sending', 'sent')
ORDER BY sent_at
`

// Non-terminal Twilio message statuses: accepted, scheduled, queued, sending, sent
// "sent" means the carrier accepted the message but delivery is not yet confirmed;
// polling continues until "delivered" or a terminal failure status is received.
func (q *Queries) ListInFlightSMSDeliveries(ctx context.Context) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listInFlightSMSDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.NotificationID,
			&i.Group,
			&i.Member,
			&i.Destination,
			&i.Channel,
			&i.Status,
			&i.EmailTemplate,
			&i.EmailVars,
			&i.Attempt,
			&i.PollAttempts,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CompletedAt,
			&i.TwilioSid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInFlightVoiceDeliveries = `-- name: ListInFlightVoiceDeliveries :many
SELECT id, delivery_id, notification_id, "group", member, destination, channel, status, email_template, email_vars, attempt, poll_attempts, error_message, sent_at, completed_at, twilio_sid FROM deliveries
WHERE channel = 'voice'
  AND status IN ('queued', 'ringing', 'in-progress')
ORDER BY sent_at
`

// Non-terminal Twilio voice statuses: queued, ringing, in-progress
func (q *Queries) ListInFlightVoiceDeliveries(ctx context.Context) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listInFlightVoiceDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.NotificationID,
			&i.Group,
			&i.Member,
			&i.Destination,
			&i.Channel,
			&i.Status,
			&i.EmailTemplate,
			&i.EmailVars,
			&i.Attempt,
			&i.PollAttempts,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CompletedAt,
			&i.TwilioSid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByEventID = `-- name: ListNotificationsByEventID :many
SELECT id, notification_id, event_id, "groups", destinations, channels, message, status, error_message, member_count, email_template, email_vars, created_at, created_by FROM notifications WHERE event_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListNotificationsByEventID(ctx context.Context, eventID string) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.EventID,
			&i.Groups,
			&i.Destinations,
			&i.Channels,
			&i.Message,
			&i.Status,
			&i.ErrorMessage,
			&i.MemberCount,
			&i.EmailTemplate,
			&i.EmailVars,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollFailedDeliveries = `-- name: ListPollFailedDeliveries :many
SELECT id, delivery_id, notification_id, "group", member, destination, channel, status, email_template, email_vars, attempt, poll_attempts, error_message, sent_at, completed_at, twilio_sid FROM deliveries WHERE status = 'poll_failed'
`

func (q *Queries) ListPollFailedDeliveries(ctx context.Context) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listPollFailedDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.NotificationID,
			&i.Group,
			&i.Member,
			&i.Destination,
			&i.Channel,
			&i.Status,
			&i.EmailTemplate,
			&i.EmailVars,
			&i.Attempt,
			&i.PollAttempts,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CompletedAt,
			&i.TwilioSid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSMSSubscriptions = `-- name: ListSMSSubscriptions :many
SELECT username, phone, subscribed_at FROM sms_subscriptions ORDER BY subscribed_at DESC
`

func (q *Queries) ListSMSSubscriptions(ctx context.Context) ([]SmsSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listSMSSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmsSubscription
	for rows.Next() {
		var i SmsSubscription
		if err := rows.Scan(&i.Username, &i.Phone, &i.SubscribedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncGroups = `-- name: ListSyncGroups :many

SELECT id, group_name, created_at, created_by FROM sync_groups ORDER BY group_name
`

// sync_groups
func (q *Queries) ListSyncGroups(ctx context.Context) ([]SyncGroup, error) {
	rows, err := q.db.QueryContext(ctx, listSyncGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncGroup
	for rows.Next() {
		var i SyncGroup
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPollAttempts = `-- name: ResetPollAttempts :exec
UPDATE deliveries
SET poll_attempts = 0
WHERE status = 'poll_failed'
`

func (q *Queries) ResetPollAttempts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPollAttempts)
	return err
}

const updateDeliveryError = `-- name: UpdateDeliveryError :exec
UPDATE deliveries
SET error_message = ?
WHERE delivery_id = ?
`

type UpdateDeliveryErrorParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	DeliveryID   string         `json:"delivery_id"`
}

// Records an error on a delivery without changing its status or completion time.
// Called when the application fails to dispatch to the delivery service (e.g.
// network error calling Twilio or SMTP), as distinct from a terminal status
// returned by the provider.
func (q *Queries) UpdateDeliveryError(ctx context.Context, arg UpdateDeliveryErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryError, arg.ErrorMessage, arg.DeliveryID)
	return err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE deliveries
SET status = ?, completed_at = ?, error_message = ?
WHERE delivery_id = ?
`

type UpdateDeliveryStatusParams struct {
	Status       string         `json:"status"`
	CompletedAt  sql.NullString `json:"completed_at"`
	ErrorMessage sql.NullString `json:"error_message"`
	DeliveryID   string         `json:"delivery_id"`
}

// error_message should include the Twilio error code when applicable,
// e.g. "queue overflow: 30001"
func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryStatus,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.DeliveryID,
	)
	return err
}

const updateEmailTemplate = `-- name: UpdateEmailTemplate :exec
UPDATE email_templates
SET subject = ?, body = ?, required_vars = ?, description = ?
WHERE template_name = ?
`

type UpdateEmailTemplateParams struct {
	Subject      string         `json:"subject"`
	Body         string         `json:"body"`
	RequiredVars string         `json:"required_vars"`
	Description  sql.NullString `json:"description"`
	TemplateName string         `json:"template_name"`
}

func (q *Queries) UpdateEmailTemplate(ctx context.Context, arg UpdateEmailTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailTemplate,
		arg.Subject,
		arg.Body,
		arg.RequiredVars,
		arg.Description,
		arg.TemplateName,
	)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET event_url = ?, event_name = ?, event_description = ?, event_severity = ?,
    modified_by = ?, modified_at = ?
WHERE event_id = ?
RETURNING id, event_id, event_url, event_name, event_description, event_severity, start_time, end_time, created_by, created_at, modified_by, modified_at
`

type UpdateEventParams struct {
	EventUrl         sql.NullString `json:"event_url"`
	EventName        sql.NullString `json:"event_name"`
	EventDescription sql.NullString `json:"event_description"`
	EventSeverity    sql.NullString `json:"event_severity"`
	ModifiedBy       sql.NullString `json:"modified_by"`
	ModifiedAt       sql.NullString `json:"modified_at"`
	EventID          string         `json:"event_id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.EventUrl,
		arg.EventName,
		arg.EventDescription,
		arg.EventSeverity,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.EventID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventUrl,
		&i.EventName,
		&i.EventDescription,
		&i.EventSeverity,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ModifiedBy,
		&i.ModifiedAt,
	)
	return i, err
}

const updateEventEndTime = `-- name: UpdateEventEndTime :exec
UPDATE events SET end_time = ?, modified_at = ?, modified_by = ? WHERE event_id = ?
`

type UpdateEventEndTimeParams struct {
	EndTime    sql.NullString `json:"end_time"`
	ModifiedAt sql.NullString `json:"modified_at"`
	ModifiedBy sql.NullString `json:"modified_by"`
	EventID    string         `json:"event_id"`
}

func (q *Queries) UpdateEventEndTime(ctx context.Context, arg UpdateEventEndTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateEventEndTime,
		arg.EndTime,
		arg.ModifiedAt,
		arg.ModifiedBy,
		arg.EventID,
	)
	return err
}

const updateNotificationMemberCount = `-- name: UpdateNotificationMemberCount :exec
UPDATE notifications SET member_count = ? WHERE notification_id = ?
`

type UpdateNotificationMemberCountParams struct {
	MemberCount    int64  `json:"member_count"`
	NotificationID string `json:"notification_id"`
}

func (q *Queries) UpdateNotificationMemberCount(ctx context.Context, arg UpdateNotificationMemberCountParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationMemberCount, arg.MemberCount, arg.NotificationID)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications SET status = ?, error_message = ? WHERE notification_id = ?
`

type UpdateNotificationStatusParams struct {
	Status         string         `json:"status"`
	ErrorMessage   sql.NullString `json:"error_message"`
	NotificationID string         `json:"notification_id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationStatus, arg.Status, arg.ErrorMessage, arg.NotificationID)
	return err
}
